dbcontroller: Remove old migration code
dlang/dub-registry pull request #532
Opened 2022-10-18 08:10 UTC by Geod24

Was looking at adding a migration myself, and obviously there is a bit of legacy that we can (and should) clean up first.

2022-10-18 21:08 UTC, WebFreak001 requested changes

2022-10-18 21:08 UTC, WebFreak001 commented on source/dubregistry/dbcontroller.d
> -		m_packages.ensureIndex([tuple("name", 1)], IndexFlags.Unique);
you are dropping indices here, I don't think these should be dropped

2022-10-19 08:28 UTC, Geod24 commented
@WebFreak001 : Rebased, fixed

2022-10-19 13:06 UTC, WebFreak001 approved these changes

2022-10-19 13:08 UTC, merged